# Generated by Django 3.0.6 on 2020-05-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Кот', 'verbose_name_plural': 'Кот'},
        ),
        migrations.AlterModelOptions(
            name='characteristics',
            options={'verbose_name': 'Характеристики', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='typeofwool',
            options={'verbose_name': 'Тип шерсти', 'verbose_name_plural': 'Тип шерсти'},
        ),
    ]
