# Generated by Django 3.0.6 on 2020-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_auto_20200520_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='style',
            field=models.CharField(default='example1 example2', max_length=100, verbose_name='Стиль для списка'),
        ),
    ]
