# Generated by Django 3.0.6 on 2020-06-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_typeofwool_text_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='img_for_list',
            field=models.ImageField(default=models.ImageField(upload_to='', verbose_name='Изображение'), upload_to='', verbose_name='Изображение 2'),
        ),
    ]
