# Generated by Django 3.0.6 on 2020-05-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20200509_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активность',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Привязанность')),
            ],
            options={
                'verbose_name': 'Привязанность',
                'verbose_name_plural': 'Привязанность',
            },
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Уход')),
            ],
            options={
                'verbose_name': 'Уход',
                'verbose_name_plural': 'Уход',
            },
        ),
        migrations.CreateModel(
            name='Life_style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Образ жизни')),
            ],
            options={
                'verbose_name': 'Образ жизни',
                'verbose_name_plural': 'Образ жизни',
            },
        ),
        migrations.CreateModel(
            name='Noisiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Разговорчивость')),
            ],
            options={
                'verbose_name': 'Разговорчивость',
                'verbose_name_plural': 'Разговорчивость',
            },
        ),
        migrations.CreateModel(
            name='Sociability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Общительность')),
            ],
            options={
                'verbose_name': 'Общительность',
                'verbose_name_plural': 'Общительность',
            },
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Activity', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Attachment', verbose_name='Привязанность'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Care', verbose_name='Уход'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='life_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Life_style', verbose_name='Образ жизни'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='noisiness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Noisiness', verbose_name='Разговорчивость'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='sociability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Sociability', verbose_name='Общительность'),
        ),
    ]
