# Generated by Django 3.0.6 on 2020-05-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20200509_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='img_for_list',
            field=models.ImageField(default=models.ImageField(upload_to='image/', verbose_name='Изображение'), upload_to='image/', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='qualities',
            field=models.CharField(max_length=500, verbose_name='Качества'),
        ),
    ]
