# Generated by Django 3.0.6 on 2020-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_cat_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image_style',
            field=models.CharField(default='e-photo', max_length=100, verbose_name='Стиль отображения картинки'),
        ),
        migrations.AddField(
            model_name='cat',
            name='text_style',
            field=models.CharField(default='e-ph-text', max_length=100, verbose_name='Стиль отбражения текста'),
        ),
    ]
